export const household = [
  {
    id: 1,
    name: "Banana Cover",
    image: "../../household/banana-cover.jpeg",
    price: 50,
  },
  {
    id: 2,
    name: "Tooth-Brush Holder",
    image: "../../household/brush-holder.jpeg",
    price: 70,
  },
  {
    id: 3,
    name: "Door Draft",
    image: "../../household/door-draft.jpeg",
    price: 70,
  },
  {
    id: 4,
    name: "Hanger",
    image: "../../household/hanger.jpeg",
    price: 200,
  },
  {
    id: 5,
    name: "Ice Tray",
    image: "../../household/ice-tray.jpeg",
    price: 90,
  },
  {
    id: 6,
    name: "Ice Roller",
    image: "../../household/ice-roller.jpeg",
    price: 85,
  },
  {
    id: 7,
    name: "Oil Dispenser",
    image: "../../household/oil bottle.jpeg",
    price: 120,
  },
  {
    id: 8,
    name: "Oil Spray",
    image: "../../household/oil-spray.jpeg",
    price: 120,
  },
  {
    id: 9,
    name: "2in1 Soap Dispenser",
    image: "../../household/soap-holder.jpeg",
    price: 120,
  },
  {
    id: 10,
    name: "Soap Stand",
    image: "../../household/soap-stand.jpeg",
    price: 60,
  },
  {
    id: 11,
    name: "Soap Case",
    image: "../../household/soap-dish.jpeg",
    price: 60,
  },
  {
    id: 12,
    name: "Stainsteel Straws",
    image: "../../household/straw.jpeg",
    price: 100,
  },
  {
    id: 13,
    name: "3-in-1 Wiper",
    image: "../../household/wiper.jpeg",
    price: 220,
  },
  {
    id: 342,
    name: "Wiper",
    image: "../../household/wiper-s.jpeg",
    price: 130,
  },
  {
    id: 14,
    name: "Vacuum Cleaner",
    image: "../../household/vacuum-cleaner.jpeg",
    price: 380,
  },
  {
    id: 15,
    name: "Washbag",
    image: "../../household/washbag.jpeg",
    price: 370,
  },
  {
    id: 16,
    name: "Utensils Scrub",
    image: "../../household/utensil-scrub.jpeg",
    price: 40,
  },
  {
    id: 17,
    name: "Body Scrub",
    image: "../../household/scrub.jpeg",
    price: 80,
  },
  {
    id: 18,
    name: "Forever Young Bag",
    image: "../../household/rubber-bag.jpeg",
    price: 260,
  },
  {
    id: 19,
    name: "Ladies HandBag",
    image: "../../household/lady-bags.jpeg",
    price: 270,
  },
  {
    id: 20,
    name: "Machine Tabs(10)",
    image: "../../household/mchn-tablets.jpeg",
    price: 120,
  },
  {
    id: 21,
    name: "Purse Organiser",
    image: "../../household/purse-organiser.jpeg",
    price: 220,
  },
  {
    id: 22,
    name: "Arm Sleeves",
    image: "../../household/hand-sleeves.jpeg",
    price: 60,
  },
  {
    id: 23,
    name: "Clothes Line",
    image: "../../household/clothes-line.jpeg",
    price: 70,
  },
  {
    id: 24,
    name: "Anti-Skid Mat",
    image: "../../household/kitchen-mat.jpeg",
    price: 300,
  },
  {
    id: 25,
    name: "Insulated Lunch Bag",
    image: "../../household/office-bag.jpeg",
    price: 120,
  },
  {
    id: 26,
    name: "Round Lunch Bag",
    image: "../../household/lunch-bag.jpeg",
    price: 200,
  },
  {
    id: 27,
    name: "Blanket Bag",
    image: "../../household/blanket-bag.jpeg",
    price: 250,
  },
  {
    id: 28,
    name: "100Ltr Storage",
    image: "../../household/100ltrbag.jpeg",
    price: 550,
  },
  {
    id: 341,
    name: "Stackable Storage",
    image: "../../household/storage-bag.jpeg",
    price: 200,
  },
  {
    id: 427,
    name: "Drawer Organiser",
    image: "../../household/bag1.jpeg",
    price: 70,
  },
  {
    id: 429,
    name: "66Ltr Bag",
    image: "../../household/bag2.jpeg",
    price: 350,
  },
  {
    id: 428,
    name: "26Ltr Bag",
    image: "../../household/26bag.jpg",
    price: 220,
  },
  {
    id: 29,
    name: "Under-Garments Bag",
    image: "../../household/ug.jpeg",
    price: 100,
  },
  {
    id: 30,
    name: "Folding Bag",
    image: "../../household/folding-bag.jpeg",
    price: 330,
  },
  {
    id: 31,
    name: "66Ltr Bag",
    image: "../../household/clothes-storage.jpeg",
    price: 350,
  },
  {
    id: 32,
    name: "Organiser",
    image: "../../household/storage.jpeg",
    price: 120,
  },
  {
    id: 33,
    name: "Rainbow Umbrella",
    image: "../../household/rainbow.jpeg",
    price: 320,
  },
  {
    id: 34,
    name: "Magic Umbrella",
    image: "../../household/magic.jpeg",
    price: 260,
  },
  {
    id: 35,
    name: "Capsule Umbrella",
    image: "../../household/capsule.jpeg",
    price: 330,
  },
  {
    id: 487,
    name: "Bottle Umbrella",
    image: "../../household/bottle-umbr.jpeg",
    price: 310,
  },
  {
    id: 36,
    name: "Kids Umbrella",
    image: "../../household/kids.jpeg",
    price: 250,
  },
  {
    id: 37,
    name: "Vacuum Flask",
    image: "../../household/vacuum-flask.jpeg",
    price: 300,
  },
  {
    id: 343,
    name: "Deer Glass Bottle",
    image: "../../household/deer-bottle.jpeg",
    price: 200,
  },
  {
    id: 38,
    name: "Roti Wrap",
    image: "../../household/roti-wrap.jpeg",
    price: 150,
  },
  {
    id: 39,
    name: "Food Wraps(1kg)",
    image: "../../household/food-wraps.jpeg",
    price: 300,
  },
  {
    id: 434,
    name: "Potato Masher",
    image: "../../household/masher.jpeg",
    price: 280,
  },
  {
    id: 40,
    name: "Dry-Fruit Cutter",
    image: "../../household/dryfruit-cutter.jpeg",
    price: 120,
  },
  {
    id: 431,
    name: "Coffee Beater",
    image: "../../household/beater1.jpeg",
    price: 120,
  },
  {
    id: 41,
    name: "Poly Organiser",
    image: "../../household/poly-organiser.jpeg",
    price: 80,
  },
  {
    id: 42,
    name: "Bathroom Organiser",
    image: "../../household/organiser.jpeg",
    price: 250,
  },
  {
    id: 43,
    name: "Grease Cleaner",
    image: "../../household/kitchen-cleaner.jpeg",
    price: 120,
  },
  {
    id: 44,
    name: "Water Dispenser",
    image: "../../household/water-dispenser.jpeg",
    price: 270,
  },
  {
    id: 46,
    name: "Bath Belt",
    image: "../../household/Bath-belt.jpeg",
    price: 100,
  },
  {
    id: 47,
    name: "Keyring Light",
    image: "../../household/keyring-light.jpeg",
    price: 120,
  },
  {
    id: 48,
    name: "Bed LED Light",
    image: "../../household/bed-light.jpeg",
    price: 200,
  },
  {
    id: 478,
    name: "360° Night Lamp Projector",
    image: "../../household/light.jpeg",
    price: 290,
  },
  {
    id: 49,
    name: "Adhesive Hook",
    image: "../../household/Adhesive-hook.jpeg",
    price: 135,
  },
  {
    id: 430,
    name: "Adhesive Hook(10pcs)",
    image: "../../household/hook.jpeg",
    price: 70,
  },
  {
    id: 50,
    name: "Oil Pump",
    image: "../../household/oil-pump.jpg",
    price: 135,
  },
  {
    id: 51,
    name: "Oil Dispenser",
    image: "../../household/oil.jpeg",
    price: 150,
  },
  {
    id: 52,
    name: "Lint Remover",
    image: "../../household/lintremover.jpeg",
    price: 135,
  },
  {
    id: 53,
    name: "Shoe Cleaner",
    image: "../../household/shoe.jpeg",
    price: 100,
  },
  {
    id: 54,
    name: "Mat(6 pcs set)",
    image: "../../household/mat1.jpeg",
    price: 200,
  },
  {
    id: 55,
    name: "Mat(6 pcs set)",
    image: "../../household/mat2.jpeg",
    price: 200,
  },
  {
    id: 56,
    name: "Mat(6 pcs set)",
    image: "../../household/mat3.jpeg",
    price: 200,
  },
  {
    id: 57,
    name: "Mat(6 pcs set)",
    image: "../../household/mat4.jpeg",
    price: 200,
  },
  {
    id: 479,
    name: "Water Absorbing Mat",
    image: "../../household/mat5.jpeg",
    price: 170,
  },
  {
    id: 58,
    name: "Sealing Machine",
    image: "../../household/seal.jpeg",
    price: 280,
  },
  {
    id: 432,
    name: "Weighing Scale",
    image: "../../household/weigh.jpeg",
    price: 250,
  },
  {
    id: 59,
    name: "Clip Rope",
    image: "../../household/rope.jpeg",
    price: 120,
  },
  {
    id: 60,
    name: "Rechargable Lighter",
    image: "../../household/lighter.jpeg",
    price: 300,
  },
  {
    id: 344,
    name: "Car WindScreen Cover",
    image: "../../household/car-shield.jpeg",
    price: 240,
  },
  {
    id: 433,
    name: "Car Foam Cleaner",
    image: "../../household/car.jpeg",
    price: 250,
  },
];

export const bangles = [
  {
    id: 61,
    image: "../../bangles/bangles1.jpeg",
  },
  {
    id: 62,
    image: "../../bangles/bangles2.jpeg",
  },
  {
    id: 63,
    image: "../../bangles/bangles3.jpeg",
  },
  {
    id: 64,
    image: "../../bangles/bangles4.jpeg",
    name: "",
  },
  {
    id: 65,
    image: "../../bangles/bangles5.jpeg",
  },
  {
    id: 66,
    image: "../../bangles/bangles6.jpeg",
  },
  {
    id: 67,
    image: "../../bangles/bangles7.jpeg",
  },
  {
    id: 68,
    image: "../../bangles/bangles8.jpeg",
  },
  {
    id: 69,
    image: "../../bangles/bangles9.jpeg",
  },
  {
    id: 70,
    image: "../../bangles/bangles10.jpeg",
  },
  {
    id: 71,
    image: "../../bangles/bangles11.jpeg",
    name: "Couple Wedding Bangles",
  },
];

export const decorations = [
  {
    id: 298,
    image: "../../decorations/dec1.jpeg",
  },
  {
    id: 299,
    image: "../../decorations/dec2.jpeg",
  },
  {
    id: 300,
    image: "../../decorations/dec3.jpeg",
  },
  {
    id: 302,
    image: "../../decorations/dec5.jpeg",
  },
  {
    id: 303,
    image: "../../decorations/dec6.jpeg",
  },
  {
    id: 304,
    image: "../../decorations/dec7.jpeg",
  },
  {
    id: 305,
    image: "../../decorations/dec8.jpeg",
  },
  {
    id: 306,
    image: "../../decorations/dec9.jpeg",
  },
  {
    id: 307,
    image: "../../decorations/dec10.jpeg",
  },
  {
    id: 308,
    image: "../../decorations/dec11.jpeg",
  },
  {
    id: 309,
    image: "../../decorations/dec12.jpeg",
  },
  {
    id: 310,
    image: "../../decorations/dec13.jpeg",
  },
  {
    id: 311,
    image: "../../decorations/dec14.jpeg",
  },
];

export const pooja = [
  {
    id: 117,
    name: "Ghee Diyas",
    image: "../../pooja/ghee-diya.jpeg",
    price: 70,
  },
  {
    id: 118,
    name: "Dhoop Cones",
    image: "../../pooja/dhoop-cones.jpeg",
    price: 55,
  },
  { id: 119, name: "Loban", image: "../../pooja/loban.jpeg", price: 85 },
];

export const rakhi = [
  {
    id: 462,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper1.jpeg",
    price: 1100,
  },
  {
    id: 463,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper2.jpeg",
    price: 1100,
  },
  {
    id: 464,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper3.jpeg",
    price: 1299,
  },
  {
    id: 465,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper4.jpeg",
    price: 699,
  },
  {
    id: 466,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper5.jpeg",
    price: 1399,
  },
  {
    id: 467,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper6.jpeg",
    price: 499,
  },
  {
    id: 449,
    name: "Rakhi Gift Set",
    image: "../../personalised/wallet4.jpeg",
    price: "450",
  },
  {
    id: 221,
    name: "Rakhi Gift Set",
    image: "../../personalised/still4.jpeg",
    price: "399",
  },
  {
    id: 251,
    name: "Rakhi Gift Set",
    image: "../../personalised/rakhi2.jpeg",
    price: "399",
  },
  {
    id: 481,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper7.jpeg",
    price: "550",
  },
  {
    id: 482,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper8.jpeg",
    price: "800",
  },
  {
    id: 483,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper9.jpeg",
    price: "499",
  },
  {
    id: 488,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper10.jpeg",
    price: "799",
  },
  {
    id: 72,
    name: "Soan Pair",
    image: "../../rakhi/godrakhi.jpeg",
    price: 50,
  },
  {
    id: 345,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi55.jpeg",
    price: 220,
  },
  {
    id: 346,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi56.jpeg",
    price: 220,
  },
  {
    id: 347,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi57.jpeg",
    price: 220,
  },
  {
    id: 348,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi58.jpeg",
    price: 220,
  },
  {
    id: 349,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi59.jpeg",
    price: 220,
  },
  {
    id: 350,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi60.jpeg",
    price: 220,
  },
  {
    id: 351,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi61.jpeg",
    price: 220,
  },
  {
    id: 352,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi62.jpeg",
    price: 220,
  },
  {
    id: 353,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi63.jpeg",
    price: 220,
  },
  {
    id: 354,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi64.jpeg",
    price: 220,
  },
  {
    id: 355,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi65.jpeg",
    price: 220,
  },
  {
    id: 356,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi66.jpeg",
    price: 220,
  },
  {
    id: 357,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi67.jpeg",
    price: 220,
  },
  {
    id: 358,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi68.jpeg",
    price: 120,
  },
  {
    id: 359,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi69.jpeg",
    price: 350,
  },
  {
    id: 360,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi70.jpeg",
    price: 300,
  },
  {
    id: 361,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi71.jpeg",
    price: 250,
  },
  {
    id: 362,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi72.jpeg",
    price: 160,
  },
  {
    id: 363,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi73.jpeg",
    price: 160,
  },
  {
    id: 366,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi76.jpeg",
    price: 160,
  },
  {
    id: 367,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi77.jpeg",
    price: 160,
  },
  {
    id: 368,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi78.jpeg",
    price: 160,
  },
  {
    id: 369,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi79.jpeg",
    price: 160,
  },
  {
    id: 370,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi80.jpeg",
    price: 160,
  },
  {
    id: 371,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi81.jpeg",
    price: 160,
  },
  {
    id: 372,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi82.jpeg",
    price: 160,
  },
  {
    id: 373,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi83.jpeg",
    price: 160,
  },
  {
    id: 374,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi84.jpeg",
    price: 160,
  },
  {
    id: 73,
    name: "Pair Rakhi",
    image: "../../rakhi/god-rakhi.jpeg",
    price: 200,
  },
  {
    id: 74,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi1.jpeg",
    price: 300,
  },
  {
    id: 75,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi2.jpeg",
    price: 160,
  },
  {
    id: 76,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi3.jpeg",
    price: 300,
  },
  {
    id: 77,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi4.jpeg",
    price: 150,
  },
  {
    id: 78,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi5.jpeg",
    price: 200,
  },
  {
    id: 79,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi6.jpeg",
    price: 250,
  },
  {
    id: 80,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi7.jpeg",
    price: 240,
  },
  {
    id: 81,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi8.jpeg",
    price: 240,
  },
  {
    id: 82,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi9.jpeg",
    price: 160,
  },
  {
    id: 337,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi51.jpeg",
    price: 180,
  },
  {
    id: 338,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi52.jpeg",
    price: 180,
  },
  {
    id: 339,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi53.jpeg",
    price: 180,
  },
  {
    id: 340,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi54.jpeg",
    price: 180,
  },
  {
    id: 83,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi10.jpeg",
    price: 200,
  },
  {
    id: 84,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi11.jpeg",
    price: 250,
  },
  {
    id: 85,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi12.jpeg",
    price: 250,
  },
  {
    id: 86,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi13.jpeg",
    price: 200,
  },
  {
    id: 87,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi14.jpeg",
    price: 160,
  },
  {
    id: 88,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi15.jpeg",
    price: 150,
  },
  {
    id: 89,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi16.jpeg",
    price: 200,
  },
  {
    id: 90,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi17.jpeg",
    price: 250,
  },
  {
    id: 91,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi.jpeg",
    price: 50,
  },
  {
    id: 92,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi1.jpeg",
    price: 50,
  },
  {
    id: 93,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi2.jpeg",
    price: 50,
  },
  {
    id: 97,
    name: "Lotus Rakhi",
    image: "../../rakhi/rakhi6.jpeg",
    price: 60,
  },
  { id: 98, name: "Om Rakhi", image: "../../rakhi/rakhi7.jpeg", price: 170 },
  {
    id: 281,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi12.jpeg",
    price: 120,
  },
  {
    id: 282,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi13.jpeg",
    price: 30,
  },
  {
    id: 283,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi14.jpeg",
    price: 120,
  },
  {
    id: 284,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi15.jpeg",
    price: 120,
  },
  {
    id: 285,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi16.jpeg",
    price: 60,
  },
  {
    id: 286,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi17.jpeg",
    price: 60,
  },
  {
    id: 287,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi18.jpeg",
    price: 60,
  },
  {
    id: 288,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi19.jpeg",
    price: 60,
  },
  {
    id: 289,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi20.jpeg",
    price: 60,
  },
  {
    id: 290,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi21.jpeg",
    price: 60,
  },
  {
    id: 291,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi22.jpeg",
    price: 120,
  },
  {
    id: 292,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi23.jpeg",
    price: 120,
  },
  {
    id: 293,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi24.jpeg",
    price: 60,
  },
  {
    id: 294,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi25.jpeg",
    price: 80,
  },
  {
    id: 312,
    name: "Rakhi",
    image: "../../rakhi/rakhi26.jpeg",
    price: 70,
  },
  {
    id: 313,
    name: "Rakhi",
    image: "../../rakhi/rakhi27.jpeg",
    price: 70,
  },
  {
    id: 314,
    name: "Rakhi",
    image: "../../rakhi/rakhi28.jpeg",
    price: 70,
  },
  {
    id: 315,
    name: "Rakhi",
    image: "../../rakhi/rakhi29.jpeg",
    price: 70,
  },
  {
    id: 317,
    name: "Rakhi",
    image: "../../rakhi/rakhi31.jpeg",
    price: 65,
  },
  { id: 375, name: "Rakhi", image: "../../rakhi/rakhi85.jpeg", price: 80 },
  {
    id: 318,
    name: "Rakhi",
    image: "../../rakhi/rakhi32.jpeg",
    price: 60,
  },
  {
    id: 319,
    name: "Rakhi",
    image: "../../rakhi/rakhi33.jpeg",
    price: 60,
  },
  {
    id: 320,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi34.jpeg",
    price: 100,
  },
  {
    id: 321,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi35.jpeg",
    price: 70,
  },
  {
    id: 322,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi36.jpeg",
    price: 70,
  },
  {
    id: 323,
    name: "Rakhi",
    image: "../../rakhi/rakhi37.jpeg",
    price: 80,
  },
  {
    id: 324,
    name: "Rakhi",
    image: "../../rakhi/rakhi38.jpeg",
    price: 80,
  },
  {
    id: 325,
    name: "Rakhi",
    image: "../../rakhi/rakhi39.jpeg",
    price: 260,
  },
  {
    id: 326,
    name: "Rakhi",
    image: "../../rakhi/rakhi40.jpeg",
    price: 125,
  },
  {
    id: 327,
    name: "Rakhi",
    image: "../../rakhi/rakhi41.jpeg",
    price: 60,
  },
  {
    id: 328,
    name: "Rakhi",
    image: "../../rakhi/rakhi42.jpeg",
    price: 60,
  },
  {
    id: 329,
    name: "Rakhi",
    image: "../../rakhi/rakhi43.jpeg",
    price: 90,
  },
  {
    id: 330,
    name: "Rakhi",
    image: "../../rakhi/rakhi44.jpeg",
    price: 50,
  },
  {
    id: 331,
    name: "Rakhi",
    image: "../../rakhi/rakhi45.jpeg",
    price: 80,
  },
  {
    id: 332,
    name: "Rakhi",
    image: "../../rakhi/rakhi46.jpeg",
    price: 80,
  },
  {
    id: 333,
    name: "Rakhi",
    image: "../../rakhi/rakhi47.jpeg",
    price: 80,
  },
  {
    id: 334,
    name: "Rakhi",
    image: "../../rakhi/rakhi48.jpeg",
    price: 55,
  },
  { id: 376, name: "Rakhi", image: "../../rakhi/rakhi86.jpeg", price: 80 },
  { id: 377, name: "Rakhi", image: "../../rakhi/rakhi87.jpeg", price: 80 },
  { id: 378, name: "Rakhi", image: "../../rakhi/rakhi88.jpeg", price: 80 },
  {
    id: 379,
    name: "Shyam Baba Rakhi",
    image: "../../rakhi/rakhi89.jpeg",
    price: 80,
  },
  {
    id: 380,
    name: "Flute Rakhi",
    image: "../../rakhi/rakhi90.jpeg",
    price: 80,
  },
  {
    id: 381,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi91.jpeg",
    price: 80,
  },
  { id: 382, name: "Sikh Rakhi", image: "../../rakhi/rakhi92.jpeg", price: 80 },
  { id: 383, name: "Rakhi", image: "../../rakhi/rakhi93.jpeg", price: 120 },
  { id: 384, name: "Rakhi", image: "../../rakhi/rakhi94.jpeg", price: 120 },
  { id: 385, name: "Rakhi", image: "../../rakhi/rakhi95.jpeg", price: 120 },
  { id: 386, name: "Rakhi", image: "../../rakhi/rakhi96.jpeg", price: 120 },
  { id: 387, name: "Rakhi", image: "../../rakhi/rakhi97.jpeg", price: 120 },
  { id: 388, name: "Rakhi", image: "../../rakhi/rakhi98.jpeg", price: 120 },
  { id: 389, name: "Rakhi", image: "../../rakhi/rakhi99.jpeg", price: 120 },
  { id: 390, name: "Rakhi", image: "../../rakhi/rakhi100.jpeg", price: 120 },
  {
    id: 391,
    name: "Trishool Rakhi",
    image: "../../rakhi/rakhi101.jpeg",
    price: 120,
  },
  { id: 392, name: "Rakhi", image: "../../rakhi/rakhi102.jpeg", price: 120 },
  { id: 393, name: "Rakhi", image: "../../rakhi/rakhi103.jpeg", price: 120 },
  { id: 394, name: "Rakhi", image: "../../rakhi/rakhi104.jpeg", price: 120 },
  {
    id: 395,
    name: "Guru Ji Rakhi",
    image: "../../rakhi/rakhi105.jpeg",
    price: 120,
  },
  { id: 396, name: "Rakhi", image: "../../rakhi/rakhi106.jpeg", price: 90 },
  {
    id: 397,
    name: "Sikh Rakhi",
    image: "../../rakhi/rakhi107.jpeg",
    price: 90,
  },
  { id: 398, name: "Rakhi", image: "../../rakhi/rakhi108.jpeg", price: 90 },
  {
    id: 409,
    name: "Rakhi",
    image: "../../rakhi/rakhi109.jpeg",
    price: 90,
  },
  {
    id: 420,
    name: "Evil Eye Rakhi",
    image: "../../rakhi/rakhi113.jpeg",
    price: 90,
  },
  {
    id: 414,
    name: "Evil Eye Rakhi",
    image: "../../rakhi/rakhi114.jpeg",
    price: 90,
  },
  {
    id: 415,
    name: "Rakhi",
    image: "../../rakhi/rakhi415.jpeg",
    price: 90,
  },
  {
    id: 416,
    name: "Rakhi",
    image: "../../rakhi/rakhi416.jpeg",
    price: 90,
  },
  {
    id: 417,
    name: "Rakhi",
    image: "../../rakhi/rakhi417.jpeg",
    price: 90,
  },
  {
    id: 418,
    name: "Rakhi",
    image: "../../rakhi/rakhi418.jpeg",
    price: 90,
  },
  {
    id: 419,
    name: "Rakhi",
    image: "../../rakhi/rakhi419.jpeg",
    price: 90,
  },
  {
    id: 99,
    name: "Bhai Rakhi",
    image: "../../rakhi/rakhi8.jpeg",
    price: 170,
  },
  {
    id: 100,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi9.jpeg",
    price: 170,
  },
  {
    id: 101,
    name: "Beads Rakhi",
    image: "../../rakhi/rakhi10.jpeg",
    price: 170,
  },
  {
    id: 102,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi1.jpeg",
    price: 160,
  },
  {
    id: 489,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi421.jpeg",
    price: 200,
  },
  {
    id: 490,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi422.jpeg",
    price: 200,
  },
  {
    id: 491,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi423.jpeg",
    price: 200,
  },
  {
    id: 103,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi2.jpeg",
    price: 160,
  },
  {
    id: 104,
    name: "Rakhi/Fridge Magnet",
    image: "../../rakhi/kidsrakhi3.jpeg",
    price: 180,
  },
  {
    id: 105,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi4.jpeg",
    price: 180,
  },
  {
    id: 106,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi5.jpeg",
    price: 180,
  },
  {
    id: 277,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi6.jpeg",
    price: 80,
  },
  {
    id: 405,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi10.jpeg",
    price: 80,
  },
  {
    id: 407,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi12.jpeg",
    price: 80,
  },
  {
    id: 408,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi13.jpeg",
    price: 80,
  },
  {
    id: 409,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi109.jpeg",
    price: 110,
  },
  {
    id: 410,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi15.jpeg",
    price: 110,
  },
  {
    id: 411,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi16.jpeg",
    price: 80,
  },
  {
    id: 412,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi17.jpeg",
    price: 80,
  },
  {
    id: 413,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi18.jpeg",
    price: 80,
  },
  {
    id: 279,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi8.jpeg",
    price: 80,
  },
  {
    id: 280,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi9.jpeg",
    price: 60,
  },
  {
    id: 399,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso1.jpeg",
    price: 220,
  },
  {
    id: 400,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso2.jpeg",
    price: 220,
  },
  {
    id: 401,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso3.jpeg",
    price: 220,
  },
  {
    id: 402,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso4.jpeg",
    price: 140,
  },
  {
    id: 403,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso5.jpeg",
    price: 150,
  },
  {
    id: 404,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso6.jpeg",
    price: 150,
  },
  {
    id: 107,
    name: "Social Media Rakhi",
    image: "../../rakhi/app-rakhi1.jpeg",
    price: 120,
  },
  {
    id: 108,
    name: "Social Media Rakhi",
    image: "../../rakhi/app-rakhi2.jpeg",
    price: 120,
  },
  {
    id: 109,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi1.jpeg",
    price: 80,
  },
  {
    id: 110,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi2.jpeg",
    price: 80,
  },
  {
    id: 111,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi3.jpeg",
    price: 80,
  },
  {
    id: 112,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi4.jpeg",
    price: 100,
  },
  {
    id: 113,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack1.jpeg",
    price: 80,
  },
  {
    id: 114,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack2.jpeg",
    price: 90,
  },
  {
    id: 115,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack3.jpeg",
    price: 60,
  },
  {
    id: 116,
    name: "Rakhi & Kumkum Pack",
    image: "../../rakhi/rakhi-combo1.jpeg",
    price: 120,
  },
  {
    id: 295,
    name: "Lumba",
    image: "../../rakhi/kangan1.jpeg",
    price: 60,
  },
  {
    id: 296,
    name: "Lumba",
    image: "../../rakhi/kangan2.jpeg",
    price: 140,
  },
  {
    id: 297,
    name: "Lumba",
    image: "../../rakhi/kangan3.jpeg",
    price: 180,
  },
  {
    id: 94,
    name: "Lumba",
    image: "../../rakhi/rakhi3.jpeg",
    price: 50,
  },
  {
    id: 95,
    name: "Lumba",
    image: "../../rakhi/rakhi4.jpeg",
    price: 50,
  },
  {
    id: 96,
    name: "Lumba",
    image: "../../rakhi/rakhi5.jpeg",
    price: 50,
  },
  {
    id: 316,
    name: "Lumba",
    image: "../../rakhi/rakhi30.jpeg",
    price: 75,
  },
];

export const tricolor = [
  {
    id: 190,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle1.jpeg",
    // price: "100",
  },
  {
    id: 191,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle2.jpeg",
    // price: "100",
  },
  {
    id: 192,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle3.jpeg",
    // price: "100",
  },
  {
    id: 193,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle4.jpeg",
    // price: "100",
  },
  {
    id: 194,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle5.jpeg",
    // price: "100",
  },
  {
    id: 195,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle6.jpeg",
    // price: "100",
  },
  {
    id: 196,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle7.jpeg",
    // price: "100",
  },
  {
    id: 197,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle8.jpeg",
    // price: "100",
  },
  {
    id: 198,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle9.jpeg",
    // price: "100",
  },
  {
    id: 199,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tribangle11.jpeg",
    // price: "100",
  },
  {
    id: 200,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tribangle12.jpeg",
    // price: "100",
  },
  {
    id: 201,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle10.jpeg",
    // price: "100",
  },
  {
    id: 202,
    name: "Tri-Color Kadha",
    image: "../../tricolor/tri-kadha1.jpeg",
    // price: "100",
  },
  {
    id: 203,
    name: "Tri-Color Earrings",
    image: "../../tricolor/tri-earing.jpeg",
    // price: "100",
  },
  {
    id: 204,
    name: "Tri-Color Earrings",
    image: "../../tricolor/tri-earing2.jpeg",
    // price: "100",
  },
  {
    id: 205,
    name: "Tri-Color Hairband",
    image: "../../tricolor/tricolor-hairband1.jpeg",
    // price: "100",
  },
  {
    id: 206,
    name: "Tri-Color Hairband",
    image: "../../tricolor/tri-hairband2.jpeg",
    // price: "100",
  },
  {
    id: 207,
    name: "Tri-Color Dupatta",
    image: "../../tricolor/tri-dupatta.jpeg",
    // price: "100",
  },
];

export const accessories = [
  {
    id: 165,
    name: "Clip",
    image: "../../accessories/clip3.jpeg",
    // price: "50",
  },
  {
    id: 166,
    name: "Clip",
    image: "../../accessories/clip4.jpeg",
    // price: "50",
  },
  {
    id: 167,
    name: "Clip",
    image: "../../accessories/clip6.jpeg",
    // price: "50",
  },
  {
    id: 168,
    name: "Clip",
    image: "../../accessories/clip7.jpeg",
    // price: "50",
  },
  {
    id: 169,
    name: "Clip",
    image: "../../accessories/clip8.jpeg",
    // price: "50",
  },
  {
    id: 170,
    name: "Clip",
    image: "../../accessories/clip9.jpeg",
    // price: "50",
  },
  {
    id: 171,
    name: "Clip",
    image: "../../accessories/clip10.jpeg",
    // price: "50",
  },
  {
    id: 172,
    name: "Clip",
    image: "../../accessories/clip11.jpeg",
    // price: "50",
  },
  {
    id: 173,
    name: "Clutchers",
    image: "../../accessories/clutch1.jpeg",
    // price: "50",
  },
  {
    id: 174,
    name: "clutchers",
    image: "../../accessories/clutch2.jpeg",
    // price: "50",
  },
  {
    id: 175,
    name: "Rubber bands",
    image: "../../accessories/rubber1.jpeg",
    // price: "50",
  },
  {
    id: 176,
    name: "Rubber Bands",
    image: "../../accessories/clip2.jpeg",
    // price: "50",
  },
  {
    id: 177,
    name: "Rubber Bands",
    image: "../../accessories/clip5.jpeg",
    // price: "50",
  },
  {
    id: 178,
    name: "Rubber bands",
    image: "../../accessories/rubber2.jpeg",
    // price: "50",
  },
  {
    id: 179,
    name: "Rubber bands",
    image: "../../accessories/rubber3.jpeg",
    // price: "50",
  },
  {
    id: 180,
    name: "Rubber bands",
    image: "../../accessories/rubber4.jpeg",
    // price: "50",
  },
  {
    id: 181,
    name: "Rubber bands",
    image: "../../accessories/rubber5.jpeg",
    // price: "50",
  },
  {
    id: 182,
    name: "Rubber bands",
    image: "../../accessories/rubber6.jpeg",
    // price: "50",
  },
  {
    id: 183,
    name: "Rubber bands",
    image: "../../accessories/rubber7.jpeg",
    // price: "50",
  },
  {
    id: 184,
    name: "Rubber bands",
    image: "../../accessories/rubber.jpeg",
    // price: "50",
  },
  {
    id: 185,
    name: "Hair Band",
    image: "../../accessories/band1.jpeg",
    // price: "50",
  },
  {
    id: 186,
    name: "Hair Band",
    image: "../../accessories/band2.jpeg",
    // price: "50",
  },
  {
    id: 187,
    name: "Hair Band",
    image: "../../accessories/band3.jpeg",
    // price: "50",
  },
  {
    id: 188,
    name: "Hair Band",
    image: "../../accessories/band4.jpeg",
    // price: "50",
  },
  {
    id: 189,
    name: "Hair Band",
    image: "../../accessories/band5.jpeg",
    // price: "50",
  },
];

export const kids = [
  { id: 120, name: "Toy", image: "../../kids/toy.jpeg" },
  { id: 121, name: "Toy", image: "../../kids/duck.jpeg" },
  { id: 122, name: "Toy", image: "../../kids/toyy.jpeg" },
  { id: 123, name: "Toy", image: "../../kids/toy1.jpeg" },
  {
    id: 124,
    name: "Toy",
    image: "../../kids/toy2.jpeg",
    // images: [
    //   "../../kids/toy3.jpeg",
    //   "../../kids/toy4.jpeg",
    //   "../../kids/toy5.jpeg",
    //   "../../kids/toy6.jpeg",
    // ],
  },
  { id: 125, name: "Toy", image: "../../kids/toy3.jpeg" },
  { id: 126, name: "Toy", image: "../../kids/toy4.jpeg" },
  { id: 127, name: "Toy", image: "../../kids/toy5.jpeg" },
  { id: 128, name: "Toy", image: "../../kids/toy6.jpeg" },
  { id: 129, name: "Toy", image: "../../kids/toy7.jpeg" },
  { id: 130, name: "Toy", image: "../../kids/toy8.jpeg" },
  { id: 131, name: "Toy", image: "../../kids/toy9.jpeg" },
  { id: 132, name: "Toy", image: "../../kids/toy10.jpeg" },
  { id: 133, name: "Toy", image: "../../kids/toy11.jpeg" },
  { id: 134, name: "Toy", image: "../../kids/toy12.jpeg" },
  { id: 135, name: "Toy", image: "../../kids/toy13.jpeg" },
  { id: 136, name: "Toy", image: "../../kids/toy14.jpeg" },
  { id: 137, name: "Toy", image: "../../kids/toy15.jpeg" },
  { id: 138, name: "Toy", image: "../../kids/toy16.jpeg" },
  { id: 139, name: "Toy", image: "../../kids/toy17.jpeg" },
  { id: 140, name: "Toy", image: "../../kids/toy18.jpeg" },
  { id: 141, name: "Toy", image: "../../kids/toy19.jpeg" },
  { id: 142, name: "Toy", image: "../../kids/toy20.jpeg" },
  { id: 143, name: "Toy", image: "../../kids/toy21.jpeg" },
  { id: 144, name: "Toy", image: "../../kids/toy22.jpeg" },
  { id: 145, name: "Toy", image: "../../kids/toy23.jpeg" },
  { id: 146, name: "Toy", image: "../../kids/toy24.jpeg" },
  { id: 147, name: "Toy", image: "../../kids/toy25.jpeg" },
  { id: 148, name: "Toy", image: "../../kids/toy26.jpeg" },
  { id: 149, name: "Toy", image: "../../kids/toy27.jpeg" },
  { id: 150, name: "Toy", image: "../../kids/toy28.jpeg" },
  { id: 151, name: "Toy", image: "../../kids/toy29.jpeg" },
  { id: 152, name: "Toy", image: "../../kids/toy30.jpeg" },
  {
    id: 474,
    name: "Magnetic Chess",
    image: "../../kids/toy31.jpeg",
    price: 460,
  },
  {
    id: 475,
    name: "International Business",
    image: "../../kids/toy32.jpeg",
    price: 300,
  },
  {
    id: 476,
    name: "360° Rotating Car",
    image: "../../kids/toy33.jpeg",
    price: 960,
  },
  { id: 477, name: "SuperMarket", image: "../../kids/toy34.jpeg", price: 1900 },
  { id: 157, name: "Toy", image: "../../kids/tiffin1.jpeg" },
  { id: 424, name: "Tiffin", image: "../../kids/tiffin2.jpeg" },
  { id: 425, name: "Tiffin", image: "../../kids/tiffin3.jpeg" },
  { id: 468, name: "Tiffin", image: "../../kids/lunch2.jpeg", price: 580 },
  { id: 469, name: "Tiffin", image: "../../kids/lunch3.jpeg", price: 750 },
  { id: 470, name: "Tiffin", image: "../../kids/lunch4.jpeg", price: 570 },
  { id: 471, name: "Tiffin", image: "../../kids/lunch5.jpeg", price: 590 },
  ,
  { id: 158, name: "Toy", image: "../../kids/pen1.jpeg" },
  { id: 159, name: "Toy", image: "../../kids/pen2.jpeg" },
  { id: 160, name: "Toy", image: "../../kids/pen3.jpeg" },
  {
    id: 472,
    name: "Touch Cool Marker",
    image: "../../kids/pen4.jpeg",
    price: 240,
  },
  { id: 161, name: "Toy", image: "../../kids/clock.jpeg" },
  { id: 162, name: "Toy", image: "../../kids/box1.jpeg" },
  { id: 461, name: "Toy", image: "../../kids/pencil.jpeg" },

  { id: 163, name: "Toy", image: "../../kids/bottle1.jpeg" },
  { id: 473, name: "Toy", image: "../../kids/bottle.jpeg", price: 450 },
  {
    id: 426,
    name: "Water Bubble Machine",
    image: "../../kids/bubblemchn.jpeg",
  },
];

export const personalised = [
  {
    id: 480,
    name: "Initial DIY Kit",
    image: "../../personalised/name-kit.jpg",
    price: 320,
  },
  {
    id: 484,
    name: "Name Magnet",
    image: "../../personalised/name.jpeg",
    price: 220,
  },
  {
    id: 485,
    name: "Baby Hamper Set",
    image: "../../personalised/baby.jpeg",
    price: 799,
  },
  {
    id: 486,
    name: "Bottle & Drawing Set",
    image: "../../personalised/student.jpeg",
    price: 799,
  },
  {
    id: 208,
    name: "Personalised",
    image: "../../personalised/frame1.jpeg",
    // price: "200",
  },
  {
    id: 209,
    name: "Personalised",
    image: "../../personalised/frame2.jpeg",
    // price: "200",
  },
  {
    id: 210,
    name: "Personalised",
    image: "../../personalised/frame3.jpeg",
    // price: "200",
  },
  {
    id: 211,
    name: "Personalised",
    image: "../../personalised/frame4.jpeg",
    // price: "200",
  },
  {
    id: 212,
    name: "Personalised",
    image: "../../personalised/frame5.jpeg",
    // price: "200",
  },
  {
    id: 213,
    name: "Personalised",
    image: "../../personalised/frame6.jpeg",
    // price: "200",
  },
  {
    id: 214,
    name: "Personalised",
    image: "../../personalised/frame7.jpeg",
    // price: "200",
  },
  {
    id: 215,
    name: "Personalised",
    image: "../../personalised/frame8.jpeg",
    // price: "200",
  },
  {
    id: 216,
    name: "Personalised",
    image: "../../personalised/frame9.jpeg",
    // price: "200",
  },
  {
    id: 217,
    name: "Personalised",
    image: "../../personalised/frame10.jpeg",
    // price: "200",
  },
  {
    id: 435,
    name: "Personalised",
    image: "../../personalised/frame11.jpeg",
    // price: "200",
  },
  {
    id: 436,
    name: "Personalised",
    image: "../../personalised/frame12.jpeg",
    // price: "200",
  },
  {
    id: 437,
    name: "Personalised",
    image: "../../personalised/frame13.jpeg",
    // price: "200",
  },
  {
    id: 438,
    name: "Personalised",
    image: "../../personalised/frame14.jpeg",
    // price: "200",
  },
  {
    id: 439,
    name: "Personalised",
    image: "../../personalised/frame15.jpeg",
    // price: "200",
  },
  {
    id: 441,
    name: "Personalised",
    image: "../../personalised/frame17.jpeg",
    // price: "200",
  },
  {
    id: 442,
    name: "Personalised",
    image: "../../personalised/frame18.jpeg",
    // price: "200",
  },
  {
    id: 444,
    name: "Personalised",
    image: "../../personalised/frame20.jpeg",
    // price: "200",
  },
  {
    id: 445,
    name: "Personalised",
    image: "../../personalised/frame21.jpeg",
    // price: "200",
  },
  {
    id: 447,
    name: "Personalised",
    image: "../../personalised/frame23.jpeg",
    price: 499,
  },
  {
    id: 448,
    name: "Personalised",
    image: "../../personalised/pillow1.jpeg",
    // price: "200",
  },
  {
    id: 218,
    name: "Personalised",
    image: "../../personalised/still1.jpeg",
    // price: "200",
  },
  {
    id: 219,
    name: "Personalised",
    image: "../../personalised/still2.jpeg",
    // price: "200",
  },
  {
    id: 220,
    name: "Personalised",
    image: "../../personalised/still3.jpeg",
    // price: "200",
  },
  {
    id: 222,
    name: "Personalised",
    image: "../../personalised/still5.jpeg",
    // price: "200",
  },
  {
    id: 223,
    name: "Personalised",
    image: "../../personalised/still6.jpeg",
    // price: "200",
  },
  {
    id: 224,
    name: "Personalised",
    image: "../../personalised/still7.jpeg",
    // price: "200",
  },
  {
    id: 225,
    name: "Personalised",
    image: "../../personalised/still8.jpeg",
    // price: "200",
  },
  {
    id: 226,
    name: "Personalised",
    image: "../../personalised/still9.jpeg",
    // price: "200",
  },
  {
    id: 227,
    name: "Personalised",
    image: "../../personalised/still10.jpeg",
    // price: "200",
  },
  {
    id: 228,
    name: "Personalised",
    image: "../../personalised/still11.jpeg",
    // price: "200",
  },
  {
    id: 229,
    name: "Personalised",
    image: "../../personalised/still12.jpeg",
    // price: "200",
  },
  {
    id: 230,
    name: "Personalised",
    image: "../../personalised/still13.jpeg",
    // price: "200",
  },
  {
    id: 451,
    name: "Personalised",
    image: "../../personalised/still14.jpeg",
  },
  {
    id: 231,
    name: "Personalised",
    image: "../../personalised/bottle1.jpeg",
    // price: "200",
  },
  {
    id: 232,
    name: "Personalised",
    image: "../../personalised/bottle2.jpeg",
    // price: "200",
  },
  {
    id: 233,
    name: "Personalised",
    image: "../../personalised/bottle3.jpeg",
    // price: "200",
  },
  {
    id: 234,
    name: "Personalised",
    image: "../../personalised/bottle4.jpeg",
    // price: "200",
  },
  {
    id: 235,
    name: "Personalised",
    image: "../../personalised/bottle5.jpeg",
    // price: "200",
  },
  {
    id: 236,
    name: "Personalised",
    image: "../../personalised/cap.jpeg",
    // price: "200",
  },
  {
    id: 237,
    name: "Personalised",
    image: "../../personalised/toy.jpeg",
    // price: "200",
  },
  {
    id: 238,
    name: "Personalised",
    image: "../../personalised/toy1.jpeg",
    // price: "200",
  },
  {
    id: 239,
    name: "Personalised",
    image: "../../personalised/toy2.jpeg",
    // price: "200",
  },
  {
    id: 240,
    name: "Personalised",
    image: "../../personalised/toy3.jpeg",
    // price: "200",
  },
  {
    id: 241,
    name: "Personalised",
    image: "../../personalised/ut1.jpeg",
    // price: "200",
  },
  {
    id: 242,
    name: "Personalised",
    image: "../../personalised/ut2.jpeg",
    // price: "200",
  },
  {
    id: 243,
    name: "Personalised",
    image: "../../personalised/wallet1.jpeg",
    // price: "200",
  },
  {
    id: 244,
    name: "Personalised",
    image: "../../personalised/wallet2.jpeg",
    // price: "200",
  },
  {
    id: 245,
    name: "Personalised",
    image: "../../personalised/wallet3.jpeg",
    // price: "200",
  },
  {
    id: 450,
    name: "Personalised",
    image: "../../personalised/wallet5.jpeg",
    // price: "200",
  },
  {
    id: 246,
    name: "Personalised",
    image: "../../personalised/tiffin1.jpeg",
    // price: "200",
  },
  {
    id: 247,
    name: "Personalised",
    image: "../../personalised/tiffin2.jpeg",
    // price: "200",
  },
  {
    id: 248,
    name: "Personalised",
    image: "../../personalised/tiffin3.jpeg",
    // price: "200",
  },
  {
    id: 249,
    name: "Personalised",
    image: "../../personalised/Rakhi.jpeg",
    // price: "200",
  },
  {
    id: 450,
    name: "Personalised",
    image: "../../personalised/rakhi1.jpeg",
    // price: "200",
  },
  {
    id: 252,
    name: "Personalised",
    image: "../../personalised/rakhi3.jpeg",
    // price: "200",
  },
  {
    id: 253,
    name: "Personalised",
    image: "../../personalised/card1.jpeg",
    // price: "200",
  },
  {
    id: 254,
    name: "Personalised",
    image: "../../personalised/clock1.jpeg",
    // price: "200",
  },
  {
    id: 452,
    name: "Personalised",
    image: "../../personalised/cup1.jpeg",
  },
  {
    id: 453,
    name: "Personalised",
    image: "../../personalised/cup2.jpeg",
  },
  {
    id: 454,
    name: "Personalised",
    image: "../../personalised/cup3.jpeg",
  },
  {
    id: 455,
    name: "Personalised",
    image: "../../personalised/cup4.jpeg",
  },
  {
    id: 456,
    name: "Personalised",
    image: "../../personalised/cup5.jpeg",
  },
  {
    id: 457,
    name: "Personalised",
    image: "../../personalised/cup6.jpeg",
  },
  {
    id: 458,
    name: "Personalised",
    image: "../../personalised/cup7.jpeg",
  },
  {
    id: 459,
    name: "Personalised",
    image: "../../personalised/board1.jpeg",
  },
  {
    id: 460,
    name: "Personalised",
    image: "../../personalised/bag1.jpeg",
  },
];

export const hariyaliTeej = [
  {
    id: 255,
    name: "Bangles",
    image: "../../hariyaliteej/bangle.jpeg",
    // price: "100",
  },
  {
    id: 256,
    name: "Bangles",
    image: "../../hariyaliteej/bangle1.jpeg",
    // price: "100",
  },
  {
    id: 257,
    name: "Bangles",
    image: "../../hariyaliteej/bangle2.jpeg",
    // price: "100",
  },
  {
    id: 258,
    name: "Bangles",
    image: "../../hariyaliteej/bangle3.jpeg",
    // price: "100",
  },
  {
    id: 259,
    name: "Bangles",
    image: "../../hariyaliteej/bangle4.jpeg",
    // price: "100",
  },
  {
    id: 260,
    name: "Bangles",
    image: "../../hariyaliteej/bangle5.jpeg",
    // price: "100",
  },
  {
    id: 261,
    name: "Bangles",
    image: "../../hariyaliteej/bangle6.jpeg",
    // price: "100",
  },
  {
    id: 262,
    name: "Bangles",
    image: "../../hariyaliteej/bangle7.jpeg",
    // price: "100",
  },
  {
    id: 263,
    name: "Bangles",
    image: "../../hariyaliteej/bangle8.jpeg",
    // price: "100",
  },
  {
    id: 264,
    name: "Bangles",
    image: "../../hariyaliteej/bangle9.jpeg",
    // price: "100",
  },
  {
    id: 265,
    name: "Bangles",
    image: "../../hariyaliteej/bangle10.jpeg",
    // price: "100",
  },
  {
    id: 266,
    name: "Bangles",
    image: "../../hariyaliteej/bangle11.jpeg",
    // price: "100",
  },
  {
    id: 267,
    name: "Bangles",
    image: "../../hariyaliteej/bangle12.jpeg",
    // price: "100",
  },
  {
    id: 268,
    name: "Bangles",
    image: "../../hariyaliteej/bangle13.jpeg",
    // price: "100",
  },
  {
    id: 269,
    name: "Bangles",
    image: "../../hariyaliteej/bangle14.jpeg",
    // price: "100",
  },
  {
    id: 270,
    name: "Bangles",
    image: "../../hariyaliteej/bangle15.jpeg",
    // price: "100",
  },
  {
    id: 271,
    name: "Bangles",
    image: "../../hariyaliteej/bangle16.jpeg",
    // price: "100",
  },
  {
    id: 272,
    name: "Bangles",
    image: "../../hariyaliteej/bangle17.jpeg",
    // price: "100",
  },
  {
    id: 273,
    name: "Bindis",
    image: "../../hariyaliteej/bindi.jpeg",
    // price: "100",
  },
  {
    id: 274,
    name: "Alta",
    image: "../../hariyaliteej/alta.jpeg",
    // price: "100",
  },
  {
    id: 275,
    name: "Sindoor",
    image: "../../hariyaliteej/sindoor.jpeg",
    // price: "100",
  },
];

export const allData = [
  {
    id: 1,
    name: "Banana Cover",
    image: "../../household/banana-cover.jpeg",
    // image1: "../../household/banana-cover.jpeg",
    price: 50,
  },
  {
    id: 2,
    name: "Tooth-Brush Holder",
    image: "../../household/brush-holder.jpeg",
    price: 70,
  },
  {
    id: 3,
    name: "Door Draft",
    image: "../../household/door-draft.jpeg",
    price: 70,
  },
  {
    id: 4,
    name: "Hanger",
    image: "../../household/hanger.jpeg",
    price: 200,
  },
  {
    id: 5,
    name: "Ice Tray",
    image: "../../household/ice-tray.jpeg",
    price: 90,
  },
  {
    id: 6,
    name: "Ice Roller",
    image: "../../household/ice-roller.jpeg",
    price: 85,
  },
  {
    id: 7,
    name: "Oil Dispenser",
    image: "../../household/oil bottle.jpeg",
    price: 120,
  },
  {
    id: 8,
    name: "Oil Spray",
    image: "../../household/oil-spray.jpeg",
    price: 120,
  },
  {
    id: 9,
    name: "2-in-1 Soap Dispenser",
    image: "../../household/soap-holder.jpeg",
    price: 120,
  },
  {
    id: 10,
    name: "Soap Stand",
    image: "../../household/soap-stand.jpeg",
    price: 60,
  },
  {
    id: 11,
    name: "Soap Case",
    image: "../../household/soap-dish.jpeg",
    price: 60,
  },
  {
    id: 12,
    name: "Stainsteel Straws",
    image: "../../household/straw.jpeg",
    price: 100,
  },
  {
    id: 13,
    name: "3-in-1 Wiper",
    image: "../../household/wiper.jpeg",
    price: 220,
  },
  {
    id: 342,
    name: "Wiper",
    image: "../../household/wiper-s.jpeg",
    price: 130,
  },
  {
    id: 14,
    name: "Vacuum Cleaner",
    image: "../../household/vacuum-cleaner.jpeg",
    price: 380,
  },
  {
    id: 15,
    name: "Washbag",
    image: "../../household/washbag.jpeg",
    price: 370,
  },
  {
    id: 16,
    name: "Utensils Scrub",
    image: "../../household/utensil-scrub.jpeg",
    price: 40,
  },
  {
    id: 17,
    name: "Body Scrub",
    image: "../../household/scrub.jpeg",
    price: 80,
  },
  {
    id: 18,
    name: "Forever Young Bag",
    image: "../../household/rubber-bag.jpeg",
    price: 260,
  },
  {
    id: 19,
    name: "Ladies HandBag",
    image: "../../household/lady-bags.jpeg",
    price: 270,
  },
  {
    id: 20,
    name: "Washing Machine Tabs(10)",
    image: "../../household/mchn-tablets.jpeg",
    price: 120,
  },
  {
    id: 21,
    name: "Purse Organiser",
    image: "../../household/purse-organiser.jpeg",
    price: 220,
  },
  {
    id: 22,
    name: "Arm Sleeves",
    image: "../../household/hand-sleeves.jpeg",
    price: 60,
  },
  {
    id: 23,
    name: "Clothes Line",
    image: "../../household/clothes-line.jpeg",
    price: 70,
  },
  {
    id: 24,
    name: "Anti-Skid Kitchen Mat",
    image: "../../household/kitchen-mat.jpeg",
    price: 300,
  },
  {
    id: 25,
    name: "Insulated Lunch Bag",
    image: "../../household/office-bag.jpeg",
    price: 120,
  },
  {
    id: 26,
    name: "Round Lunch Bag",
    image: "../../household/lunch-bag.jpeg",
    price: 200,
  },
  {
    id: 27,
    name: "Blanket Bag",
    image: "../../household/blanket-bag.jpeg",
    price: 250,
  },
  {
    id: 28,
    name: "100Ltr Storage",
    image: "../../household/100ltrbag.jpeg",
    price: 550,
  },
  {
    id: 341,
    name: "Stackable Bag",
    image: "../../household/storage-bag.jpeg",
    price: 200,
  },
  {
    id: 427,
    name: "Drawer Organiser",
    image: "../../household/bag1.jpeg",
    price: 70,
  },
  {
    id: 429,
    name: "66Ltr Bag",
    image: "../../household/bag2.jpeg",
    price: 350,
  },
  {
    id: 428,
    name: "26Ltr Bag",
    image: "../../household/26bag.jpg",
    price: 220,
  },
  {
    id: 29,
    name: "Under-Garments Bag",
    image: "../../household/ug.jpeg",
    price: 100,
  },
  {
    id: 30,
    name: "Folding Travelling Bag",
    image: "../../household/folding-bag.jpeg",
    price: 330,
  },
  {
    id: 31,
    name: "66Ltr Storage",
    image: "../../household/clothes-storage.jpeg",
    price: 350,
  },
  {
    id: 32,
    name: "Organiser",
    image: "../../household/storage.jpeg",
    price: 120,
  },
  {
    id: 33,
    name: "Rainbow Umbrella",
    image: "../../household/rainbow.jpeg",
    price: 320,
  },
  {
    id: 34,
    name: "Magic Umbrella",
    image: "../../household/magic.jpeg",
    price: 260,
  },
  {
    id: 35,
    name: "Capsule Umbrella",
    image: "../../household/capsule.jpeg",
    price: 330,
  },
  {
    id: 487,
    name: "Bottle Umbrella",
    image: "../../household/bottle-umbr.jpeg",
    price: 310,
  },
  {
    id: 36,
    name: "Kids Umbrella",
    image: "../../household/kids.jpeg",
    price: 250,
  },
  {
    id: 37,
    name: "Vacuum Flask",
    image: "../../household/vacuum-flask.jpeg",
    price: 300,
  },
  {
    id: 343,
    name: "Deer Glass Bottle",
    image: "../../household/deer-bottle.jpeg",
    price: 200,
  },
  {
    id: 38,
    name: "Roti Wrap",
    image: "../../household/roti-wrap.jpeg",
    price: 150,
  },
  {
    id: 39,
    name: "Food Wraps(1kg)",
    image: "../../household/food-wraps.jpeg",
    price: 300,
  },
  {
    id: 434,
    name: "Potato Masher",
    image: "../../household/masher.jpeg",
    price: 280,
  },
  {
    id: 40,
    name: "Dry-Fruit Cutter",
    image: "../../household/dryfruit-cutter.jpeg",
    price: 120,
  },
  {
    id: 431,
    name: "Coffee Beater",
    image: "../../household/beater1.jpeg",
    price: 120,
  },
  {
    id: 41,
    name: "Poly Organiser",
    image: "../../household/poly-organiser.jpeg",
    price: 80,
  },
  {
    id: 42,
    name: "Bathroom Organiser",
    image: "../../household/organiser.jpeg",
    price: 250,
  },
  {
    id: 43,
    name: "Kitchen Grease Cleaner",
    image: "../../household/kitchen-cleaner.jpeg",
    price: 120,
  },
  {
    id: 44,
    name: "Water Dispenser",
    image: "../../household/water-dispenser.jpeg",
    price: 270,
  },
  {
    id: 46,
    name: "Bath Belt",
    image: "../../household/Bath-belt.jpeg",
    price: 100,
  },
  {
    id: 47,
    name: "Keyring Light",
    image: "../../household/keyring-light.jpeg",
    price: 120,
  },
  {
    id: 48,
    name: "Bed LED Light",
    image: "../../household/bed-light.jpeg",
    price: 200,
  },
  {
    id: 478,
    name: "360° Night Lamp Projector",
    image: "../../household/light.jpeg",
    price: 290,
  },
  {
    id: 49,
    name: "Adhesive Hook",
    image: "../../household/Adhesive-hook.jpeg",
    price: 135,
  },
  {
    id: 430,
    name: "Adhesive Hook(10pcs)",
    image: "../../household/hook.jpeg",
    price: 70,
  },
  {
    id: 50,
    name: "Oil Pump",
    image: "../../household/oil-pump.jpg",
    price: 135,
  },
  {
    id: 51,
    name: "Oil Dispenser",
    image: "../../household/oil.jpeg",
    price: 150,
  },
  {
    id: 52,
    name: "Lint Remover",
    image: "../../household/lintremover.jpeg",
    price: 135,
  },
  {
    id: 53,
    name: "Shoe Cleaner",
    image: "../../household/shoe.jpeg",
    price: 100,
  },
  {
    id: 54,
    name: "Mat(6 pcs set)",
    image: "../../household/mat1.jpeg",
    price: 200,
  },
  {
    id: 55,
    name: "Mat(6 pcs set)",
    image: "../../household/mat2.jpeg",
    price: 200,
  },
  {
    id: 56,
    name: "Mat(6 pcs set)",
    image: "../../household/mat3.jpeg",
    price: 200,
  },
  {
    id: 57,
    name: "Mat(6 pcs set)",
    image: "../../household/mat4.jpeg",
    price: 200,
  },
  {
    id: 479,
    name: "Mat",
    image: "../../household/mat5.jpeg",
    price: 170,
  },
  {
    id: 58,
    name: "Sealing Machine",
    image: "../../household/seal.jpeg",
    price: 280,
  },
  {
    id: 432,
    name: "Weighing Scale",
    image: "../../household/weigh.jpeg",
    price: 250,
  },
  {
    id: 59,
    name: "Clip Rope",
    image: "../../household/rope.jpeg",
    price: 120,
  },
  {
    id: 60,
    name: "Rechargable Lighter",
    image: "../../household/lighter.jpeg",
    price: 300,
  },
  {
    id: 344,
    name: "Car WindScreen Cover",
    image: "../../household/car-shield.jpeg",
    price: 240,
  },
  {
    id: 433,
    name: "Car Foam Cleaner",
    image: "../../household/car.jpeg",
    price: 250,
  },
  {
    id: 61,
    image: "../../bangles/bangles1.jpeg",
  },
  {
    id: 62,
    image: "../../bangles/bangles2.jpeg",
  },
  {
    id: 63,
    image: "../../bangles/bangles3.jpeg",
  },
  {
    id: 64,
    image: "../../bangles/bangles4.jpeg",
    name: "",
  },
  {
    id: 65,
    image: "../../bangles/bangles5.jpeg",
  },
  {
    id: 66,
    image: "../../bangles/bangles6.jpeg",
  },
  {
    id: 67,
    image: "../../bangles/bangles7.jpeg",
  },
  {
    id: 68,
    image: "../../bangles/bangles8.jpeg",
  },
  {
    id: 69,
    image: "../../bangles/bangles9.jpeg",
  },
  {
    id: 70,
    image: "../../bangles/bangles10.jpeg",
  },
  {
    id: 71,
    image: "../../bangles/bangles11.jpeg",
    name: "Couple Wedding Bangles",
  },
  {
    id: 72,
    name: "Soan Pair",
    image: "../../rakhi/godrakhi.jpeg",
    price: "50",
  },
  {
    id: 462,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper1.jpeg",
    price: 1100,
  },
  {
    id: 463,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper2.jpeg",
    price: 1100,
  },
  {
    id: 464,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper3.jpeg",
    price: 1299,
  },
  {
    id: 465,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper4.jpeg",
    price: 699,
  },
  {
    id: 466,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper5.jpeg",
    price: 1399,
  },
  {
    id: 467,
    name: "Rakhi Hamper",
    image: "../../rakhi/hamper6.jpeg",
    price: 499,
  },
  {
    id: 449,
    name: "Rakhi Gift Set",
    image: "../../personalised/wallet4.jpeg",
    price: "450",
  },
  {
    id: 221,
    name: "Rakhi Gift Set",
    image: "../../personalised/still4.jpeg",
    price: "399",
  },
  {
    id: 251,
    name: "Rakhi Gift Set",
    image: "../../personalised/rakhi2.jpeg",
    price: "399",
  },
  {
    id: 481,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper7.jpeg",
    price: "550",
  },
  {
    id: 482,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper8.jpeg",
    price: "800",
  },
  {
    id: 483,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper9.jpeg",
    price: "499",
  },
  {
    id: 488,
    name: "Rakhi Gift Set",
    image: "../../rakhi/hamper10.jpeg",
    price: "799",
  },
  {
    id: 345,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi55.jpeg",
    price: 220,
  },
  {
    id: 346,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi56.jpeg",
    price: 220,
  },
  {
    id: 347,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi57.jpeg",
    price: 220,
  },
  {
    id: 348,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi58.jpeg",
    price: 220,
  },
  {
    id: 349,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi59.jpeg",
    price: 220,
  },
  {
    id: 350,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi60.jpeg",
    price: 220,
  },
  {
    id: 351,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi61.jpeg",
    price: 220,
  },
  {
    id: 352,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi62.jpeg",
    price: 220,
  },
  {
    id: 353,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi63.jpeg",
    price: 220,
  },
  {
    id: 354,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi64.jpeg",
    price: 220,
  },
  {
    id: 355,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi65.jpeg",
    price: 220,
  },
  {
    id: 356,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi66.jpeg",
    price: 220,
  },
  {
    id: 357,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi67.jpeg",
    price: 220,
  },
  {
    id: 358,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi68.jpeg",
    price: 120,
  },
  {
    id: 359,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi69.jpeg",
    price: 350,
  },
  {
    id: 360,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi70.jpeg",
    price: 300,
  },
  {
    id: 361,
    name: "Pair Rakhi",
    image: "../../rakhi/rakhi71.jpeg",
    price: 250,
  },
  {
    id: 73,
    name: "Pair Rakhi",
    image: "../../rakhi/god-rakhi.jpeg",
    price: "200",
  },
  {
    id: 74,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi1.jpeg",
    price: "300",
  },
  {
    id: 75,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi2.jpeg",
    price: "160",
  },
  {
    id: 76,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi3.jpeg",
    price: "300",
  },
  {
    id: 77,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi4.jpeg",
    price: "150",
  },
  {
    id: 78,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi5.jpeg",
    price: "200",
  },
  {
    id: 79,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi6.jpeg",
    price: "250",
  },
  {
    id: 80,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi7.jpeg",
    price: "240",
  },
  {
    id: 81,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi8.jpeg",
    price: "240",
  },
  {
    id: 82,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi9.jpeg",
    price: "160",
  },
  {
    id: 83,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi10.jpeg",
    price: "200",
  },
  {
    id: 84,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi11.jpeg",
    price: "250",
  },
  {
    id: 85,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi12.jpeg",
    price: "250",
  },
  {
    id: 86,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi13.jpeg",
    price: "250",
  },
  {
    id: 87,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi14.jpeg",
    price: "160",
  },
  {
    id: 88,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi15.jpeg",
    price: "150",
  },
  {
    id: 89,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi16.jpeg",
    price: "200",
  },
  {
    id: 90,
    name: "Pair Rakhi",
    image: "../../rakhi/pairrakhi17.jpeg",
    price: "250",
  },
  {
    id: 91,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi.jpeg",
    price: "50",
  },
  {
    id: 92,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi1.jpeg",
    price: "50",
  },
  {
    id: 93,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi2.jpeg",
    price: "50",
  },
  {
    id: 97,
    name: "Lotus Rakhi",
    image: "../../rakhi/rakhi6.jpeg",
    price: "60",
  },
  { id: 98, name: "Om Rakhi", image: "../../rakhi/rakhi7.jpeg", price: "170" },
  {
    id: 99,
    name: "Bhai Rakhi",
    image: "../../rakhi/rakhi8.jpeg",
    price: "170",
  },
  {
    id: 276,
    name: "Swastik Rakhi",
    image: "../../rakhi/rakhi11.jpeg",
    price: "70",
  },
  {
    id: 100,
    name: "Flower Rakhi",
    image: "../../rakhi/rakhi9.jpeg",
    price: "170",
  },
  {
    id: 101,
    name: "Beads Rakhi",
    image: "../../rakhi/rakhi10.jpeg",
    price: "170",
  },
  {
    id: 281,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi12.jpeg",
    price: "120",
  },
  {
    id: 282,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi13.jpeg",
    price: "30",
  },
  {
    id: 283,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi14.jpeg",
    price: "120",
  },
  {
    id: 284,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi15.jpeg",
    price: "120",
  },
  {
    id: 285,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi16.jpeg",
    price: "60",
  },
  {
    id: 286,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi17.jpeg",
    price: "60",
  },
  {
    id: 287,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi18.jpeg",
    price: "60",
  },
  {
    id: 288,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi19.jpeg",
    price: "60",
  },
  {
    id: 289,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi20.jpeg",
    price: "60",
  },
  {
    id: 290,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi21.jpeg",
    price: "60",
  },
  {
    id: 291,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi22.jpeg",
    price: "120",
  },
  {
    id: 292,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi23.jpeg",
    price: "120",
  },
  {
    id: 293,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi24.jpeg",
    price: "60",
  },
  {
    id: 294,
    name: "Metal Rakhi",
    image: "../../rakhi/rakhi25.jpeg",
    price: "80",
  },
  {
    id: 312,
    name: "Rakhi",
    image: "../../rakhi/rakhi26.jpeg",
    price: "70",
  },
  {
    id: 313,
    name: "Rakhi",
    image: "../../rakhi/rakhi27.jpeg",
    price: "70",
  },
  {
    id: 314,
    name: "Rakhi",
    image: "../../rakhi/rakhi28.jpeg",
    price: "70",
  },
  {
    id: 315,
    name: "Rakhi",
    image: "../../rakhi/rakhi29.jpeg",
    price: "70",
  },
  {
    id: 317,
    name: "Rakhi",
    image: "../../rakhi/rakhi31.jpeg",
    price: "65",
  },
  {
    id: 318,
    name: "Rakhi",
    image: "../../rakhi/rakhi32.jpeg",
    price: "60",
  },
  {
    id: 319,
    name: "Rakhi",
    image: "../../rakhi/rakhi33.jpeg",
    price: "60",
  },
  {
    id: 320,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi34.jpeg",
    price: "100",
  },
  {
    id: 321,
    name: "Rakhi",
    image: "../../rakhi/rakhi35.jpeg",
    price: "70",
  },
  {
    id: 322,
    name: "Rakhi",
    image: "../../rakhi/rakhi36.jpeg",
    price: "70",
  },
  {
    id: 323,
    name: "Rakhi",
    image: "../../rakhi/rakhi37.jpeg",
    price: "80",
  },
  {
    id: 324,
    name: "Rakhi",
    image: "../../rakhi/rakhi38.jpeg",
    price: "80",
  },
  {
    id: 325,
    name: "Rakhi",
    image: "../../rakhi/rakhi39.jpeg",
    price: "260",
  },
  {
    id: 326,
    name: "Rakhi",
    image: "../../rakhi/rakhi40.jpeg",
    price: "125",
  },
  {
    id: 327,
    name: "Rakhi",
    image: "../../rakhi/rakhi41.jpeg",
    price: 60,
  },
  {
    id: 328,
    name: "Rakhi",
    image: "../../rakhi/rakhi42.jpeg",
    price: 60,
  },
  {
    id: 329,
    name: "Rakhi",
    image: "../../rakhi/rakhi43.jpeg",
    price: 90,
  },
  {
    id: 330,
    name: "Rakhi",
    image: "../../rakhi/rakhi44.jpeg",
    price: 50,
  },
  {
    id: 331,
    name: "Rakhi",
    image: "../../rakhi/rakhi45.jpeg",
    price: 80,
  },
  {
    id: 332,
    name: "Rakhi",
    image: "../../rakhi/rakhi46.jpeg",
    price: 80,
  },
  {
    id: 333,
    name: "Rakhi",
    image: "../../rakhi/rakhi47.jpeg",
    price: 80,
  },
  {
    id: 334,
    name: "Rakhi",
    image: "../../rakhi/rakhi48.jpeg",
    price: 55,
  },
  {
    id: 335,
    name: "Rakhi",
    image: "../../rakhi/rakhi49.jpeg",
    price: 180,
  },
  {
    id: 336,
    name: "Rakhi",
    image: "../../rakhi/rakhi50.jpeg",
    price: 180,
  },
  {
    id: 337,
    name: "Rakhi",
    image: "../../rakhi/rakhi51.jpeg",
    price: 180,
  },
  {
    id: 338,
    name: "Rakhi",
    image: "../../rakhi/rakhi52.jpeg",
    price: 180,
  },
  {
    id: 339,
    name: "Rakhi",
    image: "../../rakhi/rakhi53.jpeg",
    price: 180,
  },
  {
    id: 340,
    name: "Rakhi",
    image: "../../rakhi/rakhi54.jpeg",
    price: 180,
  },
  { id: 362, name: "Rakhi", image: "../../rakhi/rakhi72.jpeg", price: 160 },
  { id: 363, name: "Rakhi", image: "../../rakhi/rakhi73.jpeg", price: 160 },
  { id: 366, name: "Rakhi", image: "../../rakhi/rakhi76.jpeg", price: 160 },
  { id: 367, name: "Rakhi", image: "../../rakhi/rakhi77.jpeg", price: 160 },
  { id: 368, name: "Rakhi", image: "../../rakhi/rakhi78.jpeg", price: 160 },
  { id: 369, name: "Rakhi", image: "../../rakhi/rakhi79.jpeg", price: 160 },
  { id: 370, name: "Rakhi", image: "../../rakhi/rakhi80.jpeg", price: 160 },
  { id: 371, name: "Rakhi", image: "../../rakhi/rakhi81.jpeg", price: 160 },
  { id: 372, name: "Rakhi", image: "../../rakhi/rakhi82.jpeg", price: 160 },
  { id: 373, name: "Rakhi", image: "../../rakhi/rakhi83.jpeg", price: 160 },
  { id: 374, name: "Rakhi", image: "../../rakhi/rakhi84.jpeg", price: 160 },
  { id: 375, name: "Rakhi", image: "../../rakhi/rakhi85.jpeg", price: 80 },
  { id: 376, name: "Rakhi", image: "../../rakhi/rakhi86.jpeg", price: 160 },
  { id: 377, name: "Rakhi", image: "../../rakhi/rakhi87.jpeg", price: 80 },
  { id: 378, name: "Rakhi", image: "../../rakhi/rakhi88.jpeg", price: 180 },
  {
    id: 379,
    name: "Shyam Baba Rakhi",
    image: "../../rakhi/rakhi89.jpeg",
    price: 180,
  },
  {
    id: 380,
    name: "Flute Rakhi",
    image: "../../rakhi/rakhi90.jpeg",
    price: 180,
  },
  {
    id: 381,
    name: "Ganesh Ji Rakhi",
    image: "../../rakhi/rakhi91.jpeg",
    price: 180,
  },
  {
    id: 382,
    name: "Sikh Rakhi",
    image: "../../rakhi/rakhi92.jpeg",
    price: 180,
  },
  { id: 383, name: "Rakhi", image: "../../rakhi/rakhi93.jpeg", price: 120 },
  { id: 384, name: "Rakhi", image: "../../rakhi/rakhi94.jpeg", price: 120 },
  { id: 385, name: "Rakhi", image: "../../rakhi/rakhi95.jpeg", price: 120 },
  { id: 386, name: "Rakhi", image: "../../rakhi/rakhi96.jpeg", price: 120 },
  { id: 387, name: "Rakhi", image: "../../rakhi/rakhi97.jpeg", price: 120 },
  { id: 388, name: "Rakhi", image: "../../rakhi/rakhi98.jpeg", price: 120 },
  { id: 389, name: "Rakhi", image: "../../rakhi/rakhi99.jpeg", price: 120 },
  { id: 390, name: "Rakhi", image: "../../rakhi/rakhi100.jpeg", price: 120 },
  {
    id: 391,
    name: "Trishool Rakhi",
    image: "../../rakhi/rakhi101.jpeg",
    price: 120,
  },
  { id: 392, name: "Rakhi", image: "../../rakhi/rakhi102.jpeg", price: 120 },
  { id: 393, name: "Rakhi", image: "../../rakhi/rakhi103.jpeg", price: 120 },
  { id: 394, name: "Rakhi", image: "../../rakhi/rakhi104.jpeg", price: 120 },
  {
    id: 395,
    name: "Guru Ji Rakhi",
    image: "../../rakhi/rakhi105.jpeg",
    price: 120,
  },
  { id: 396, name: "Rakhi", image: "../../rakhi/rakhi106.jpeg", price: 120 },
  {
    id: 397,
    name: "Sikh Rakhi",
    image: "../../rakhi/rakhi107.jpeg",
    price: 90,
  },
  { id: 398, name: "Rakhi", image: "../../rakhi/rakhi108.jpeg", price: 90 },
  {
    id: 409,
    name: "Rakhi",
    image: "../../rakhi/rakhi109.jpeg",
    price: 90,
  },
  {
    id: 423,
    name: "Evil Eye Rakhi",
    image: "../../rakhi/rakhi113.jpeg",
    price: 90,
  },
  {
    id: 414,
    name: "Evil Eye Rakhi",
    image: "../../rakhi/rakhi114.jpeg",
    price: 90,
  },
  {
    id: 415,
    name: "Rakhi",
    image: "../../rakhi/rakhi415.jpeg",
    price: 90,
  },
  {
    id: 416,
    name: "Rakhi",
    image: "../../rakhi/rakhi416.jpeg",
    price: 90,
  },
  {
    id: 417,
    name: "Rakhi",
    image: "../../rakhi/rakhi417.jpeg",
    price: 90,
  },
  {
    id: 418,
    name: "Rakhi",
    image: "../../rakhi/rakhi418.jpeg",
    price: 90,
  },
  {
    id: 419,
    name: "Rakhi",
    image: "../../rakhi/rakhi419.jpeg",
    price: 90,
  },
  {
    id: 420,
    name: "Rakhi",
    image: "../../rakhi/rakhi420.jpeg",
    price: 90,
  },
  {
    id: 102,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi1.jpeg",
    price: "160",
  },
  {
    id: 103,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi2.jpeg",
    price: "160",
  },
  {
    id: 489,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi421.jpeg",
    price: 200,
  },
  {
    id: 490,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi422.jpeg",
    price: 200,
  },
  {
    id: 491,
    name: "Kids Rakhi",
    image: "../../rakhi/rakhi423.jpeg",
    price: 200,
  },
  {
    id: 277,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi6.jpeg",
    price: "80",
  },
  {
    id: 278,
    name: "Cartoon Rakhi",
    image: "../../rakhi/kidsrakhi7.jpeg",
    price: "80",
  },
  {
    id: 405,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi10.jpeg",
    price: 80,
  },
  {
    id: 407,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi12.jpeg",
    price: 80,
  },
  {
    id: 408,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi13.jpeg",
    price: 80,
  },
  {
    id: 409,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi14.jpeg",
    price: 110,
  },
  {
    id: 410,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi15.jpeg",
    price: 110,
  },
  {
    id: 411,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi16.jpeg",
    price: 80,
  },
  {
    id: 412,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi17.jpeg",
    price: 80,
  },
  {
    id: 413,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi18.jpeg",
    price: 80,
  },
  {
    id: 421,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi18.jpeg",
    price: 90,
  },
  {
    id: 422,
    name: "Kids Rakhi",
    image: "../../rakhi/kidsrakhi18.jpeg",
    price: 90,
  },
  {
    id: 279,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi8.jpeg",
    price: "80",
  },
  {
    id: 280,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi9.jpeg",
    price: "60",
  },
  {
    id: 399,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso1.jpeg",
    price: 220,
  },
  {
    id: 400,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso2.jpeg",
    price: 220,
  },
  {
    id: 401,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso3.jpeg",
    price: 220,
  },
  {
    id: 402,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso4.jpeg",
    price: 140,
  },
  {
    id: 403,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso5.jpeg",
    price: 150,
  },
  {
    id: 404,
    name: "Personalised Rakhi",
    image: "../../rakhi/perso6.jpeg",
    price: 150,
  },
  {
    id: 104,
    name: "Rakhi/Fridge Magnet",
    image: "../../rakhi/kidsrakhi3.jpeg",
    price: "180",
  },
  {
    id: 105,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi4.jpeg",
    price: "180",
  },
  {
    id: 106,
    name: "Personalised Rakhi",
    image: "../../rakhi/kidsrakhi5.jpeg",
    price: "180",
  },
  {
    id: 107,
    name: "Social Media Rakhi",
    image: "../../rakhi/app-rakhi1.jpeg",
    price: "120",
  },
  {
    id: 108,
    name: "Social Media Rakhi",
    image: "../../rakhi/app-rakhi2.jpeg",
    price: "120",
  },
  {
    id: 109,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi1.jpeg",
    price: "80",
  },
  {
    id: 110,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi2.jpeg",
    price: "80",
  },
  {
    id: 111,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi3.jpeg",
    price: "80",
  },
  {
    id: 112,
    name: "Dori Rakhi(Set of 12)",
    image: "../../rakhi/dhagarakhi4.jpeg",
    price: "100",
  },
  {
    id: 113,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack1.jpeg",
    price: "80",
  },
  {
    id: 114,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack2.jpeg",
    price: "90",
  },
  {
    id: 115,
    name: "Kumkum Pack",
    image: "../../rakhi/kumkum-pack3.jpeg",
    price: "60",
  },
  {
    id: 116,
    name: "Rakhi & Kumkum Pack",
    image: "../../rakhi/rakhi-combo1.jpeg",
    price: "120",
  },
  {
    id: 117,
    name: "Ghee Diyas",
    image: "../../pooja/ghee-diya.jpeg",
    price: "70",
  },
  {
    id: 118,
    name: "Dhoop Cones",
    image: "../../pooja/dhoop-cones.jpeg",
    price: "55",
  },
  {
    id: 295,
    name: "Lumba",
    image: "../../rakhi/kangan1.jpeg",
    price: 60,
  },
  {
    id: 296,
    name: "Lumba",
    image: "../../rakhi/kangan2.jpeg",
    price: 140,
  },
  {
    id: 297,
    name: "Lumba",
    image: "../../rakhi/kangan3.jpeg",
    price: 180,
  },
  {
    id: 94,
    name: "Lumba",
    image: "../../rakhi/rakhi3.jpeg",
    price: 50,
  },
  {
    id: 95,
    name: "Lumba",
    image: "../../rakhi/rakhi4.jpeg",
    price: 50,
  },
  {
    id: 96,
    name: "Lumba",
    image: "../../rakhi/rakhi5.jpeg",
    price: 50,
  },
  {
    id: 316,
    name: "Lumba",
    image: "../../rakhi/rakhi30.jpeg",
    price: 75,
  },
  { id: 119, name: "Loban", image: "../../pooja/loban.jpeg", price: "85" },
  { id: 120, name: "Toy", image: "../../kids/toy.jpeg" },
  { id: 121, name: "Toy", image: "../../kids/duck.jpeg" },
  { id: 122, name: "Toy", image: "../../kids/toyy.jpeg" },
  { id: 123, name: "Toy", image: "../../kids/toy1.jpeg" },
  {
    id: 124,
    name: "Toy",
    image: "../../kids/toy2.jpeg",
    // images: [
    //   "../../kids/toy3.jpeg",
    //   "../../kids/toy4.jpeg",
    //   "../../kids/toy5.jpeg",
    //   "../../kids/toy6.jpeg",
    // ],
  },
  { id: 125, name: "Toy", image: "../../kids/toy3.jpeg" },
  { id: 126, name: "Toy", image: "../../kids/toy4.jpeg" },
  { id: 127, name: "Toy", image: "../../kids/toy5.jpeg" },
  { id: 128, name: "Toy", image: "../../kids/toy6.jpeg" },
  { id: 129, name: "Toy", image: "../../kids/toy7.jpeg" },
  { id: 130, name: "Toy", image: "../../kids/toy8.jpeg" },
  { id: 131, name: "Toy", image: "../../kids/toy9.jpeg" },
  { id: 132, name: "Toy", image: "../../kids/toy10.jpeg" },
  { id: 133, name: "Toy", image: "../../kids/toy11.jpeg" },
  { id: 134, name: "Toy", image: "../../kids/toy12.jpeg" },
  { id: 135, name: "Toy", image: "../../kids/toy13.jpeg" },
  { id: 136, name: "Toy", image: "../../kids/toy14.jpeg" },
  { id: 137, name: "Toy", image: "../../kids/toy15.jpeg" },
  { id: 138, name: "Toy", image: "../../kids/toy16.jpeg" },
  { id: 139, name: "Toy", image: "../../kids/toy17.jpeg" },
  { id: 140, name: "Toy", image: "../../kids/toy18.jpeg" },
  { id: 141, name: "Toy", image: "../../kids/toy19.jpeg" },
  { id: 142, name: "Toy", image: "../../kids/toy20.jpeg" },
  { id: 143, name: "Toy", image: "../../kids/toy21.jpeg" },
  { id: 144, name: "Toy", image: "../../kids/toy22.jpeg" },
  { id: 145, name: "Toy", image: "../../kids/toy23.jpeg" },
  { id: 146, name: "Toy", image: "../../kids/toy24.jpeg" },
  { id: 147, name: "Toy", image: "../../kids/toy25.jpeg" },
  { id: 148, name: "Toy", image: "../../kids/toy26.jpeg" },
  { id: 149, name: "Toy", image: "../../kids/toy27.jpeg" },
  { id: 150, name: "Toy", image: "../../kids/toy28.jpeg" },
  { id: 151, name: "Toy", image: "../../kids/toy29.jpeg" },
  { id: 152, name: "Toy", image: "../../kids/toy30.jpeg" },
  {
    id: 474,
    name: "Magnetic Chess",
    image: "../../kids/toy31.jpeg",
    price: 460,
  },
  {
    id: 475,
    name: "International Business",
    image: "../../kids/toy32.jpeg",
    price: 300,
  },
  {
    id: 476,
    name: "360° Rotating Car",
    image: "../../kids/toy33.jpeg",
    price: 960,
  },
  { id: 477, name: "SuperMarket", image: "../../kids/toy34.jpeg", price: 1900 },
  { id: 157, name: "Tiffin", image: "../../kids/tiffin1.jpeg" },
  { id: 424, name: "Tiffin", image: "../../kids/tiffin2.jpeg" },
  { id: 425, name: "Tiffin", image: "../../kids/tiffin3.jpeg" },
  { id: 468, name: "Tiffin", image: "../../kids/lunch2.jpeg", price: 580 },
  { id: 469, name: "Tiffin", image: "../../kids/lunch3.jpeg", price: 750 },
  { id: 470, name: "Tiffin", image: "../../kids/lunch4.jpeg", price: 570 },
  { id: 471, name: "Tiffin", image: "../../kids/lunch5.jpeg", price: 590 },
  { id: 158, name: "Toy", image: "../../kids/pen1.jpeg" },
  { id: 159, name: "Toy", image: "../../kids/pen2.jpeg" },
  { id: 160, name: "Toy", image: "../../kids/pen3.jpeg" },
  { id: 472, name: "Toy", image: "../../kids/pen4.jpeg", price: 240 },
  { id: 161, name: "Toy", image: "../../kids/clock.jpeg" },
  { id: 162, name: "Toy", image: "../../kids/box1.jpeg" },
  { id: 461, name: "Toy", image: "../../kids/pencil.jpeg" },
  { id: 163, name: "Toy", image: "../../kids/bottle1.jpeg" },
  { id: 473, name: "Toy", image: "../../kids/bottle.jpeg", price: 450 },
  {
    id: 426,
    name: "Water Bubble Machine",
    image: "../../kids/bubblemchn.jpeg",
  },
  {
    id: 164,
    name: "Clip",
    image: "../../accessories/clip1.jpeg",
  },
  {
    id: 165,
    name: "Clip",
    image: "../../accessories/clip3.jpeg",
  },
  {
    id: 166,
    name: "Clip",
    image: "../../accessories/clip4.jpeg",
  },
  {
    id: 167,
    name: "Clip",
    image: "../../accessories/clip6.jpeg",
  },
  {
    id: 168,
    name: "Clip",
    image: "../../accessories/clip7.jpeg",
  },
  {
    id: 169,
    name: "Clip",
    image: "../../accessories/clip8.jpeg",
  },
  {
    id: 170,
    name: "Clip",
    image: "../../accessories/clip9.jpeg",
  },
  {
    id: 171,
    name: "Clip",
    image: "../../accessories/clip10.jpeg",
  },
  {
    id: 172,
    name: "Clip",
    image: "../../accessories/clip11.jpeg",
  },
  {
    id: 173,
    name: "Clutchers",
    image: "../../accessories/clutch1.jpeg",
  },
  {
    id: 174,
    name: "clutcherss",
    image: "../../accessories/clutch2.jpeg",
  },
  {
    id: 175,
    name: "Rubber bands",
    image: "../../accessories/rubber1.jpeg",
  },
  {
    id: 176,
    name: "Rubber Bands",
    image: "../../accessories/clip2.jpeg",
  },
  {
    id: 177,
    name: "Rubber Bands",
    image: "../../accessories/clip5.jpeg",
  },
  {
    id: 178,
    name: "Rubber bands",
    image: "../../accessories/rubber2.jpeg",
  },
  {
    id: 179,
    name: "Rubber bands",
    image: "../../accessories/rubber3.jpeg",
  },
  {
    id: 180,
    name: "Rubber bands",
    image: "../../accessories/rubber4.jpeg",
  },
  {
    id: 181,
    name: "Rubber bands",
    image: "../../accessories/rubber5.jpeg",
  },
  {
    id: 182,
    name: "Rubber bands",
    image: "../../accessories/rubber6.jpeg",
  },
  {
    id: 183,
    name: "Rubber bands",
    image: "../../accessories/rubber7.jpeg",
  },
  {
    id: 184,
    name: "Rubber bands",
    image: "../../accessories/rubber.jpeg",
  },
  {
    id: 185,
    name: "Hair Band",
    image: "../../accessories/band1.jpeg",
  },
  {
    id: 186,
    name: "Hair Band",
    image: "../../accessories/band2.jpeg",
  },
  {
    id: 187,
    name: "Hair Band",
    image: "../../accessories/band3.jpeg",
  },
  {
    id: 188,
    name: "Hair Band",
    image: "../../accessories/band4.jpeg",
  },
  {
    id: 189,
    name: "Hair Band",
    image: "../../accessories/band5.jpeg",
  },
  {
    id: 190,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle1.jpeg",
  },
  {
    id: 191,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle2.jpeg",
  },
  {
    id: 192,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle3.jpeg",
  },
  {
    id: 193,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle4.jpeg",
  },
  {
    id: 194,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle5.jpeg",
  },
  {
    id: 195,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle6.jpeg",
  },
  {
    id: 196,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle7.jpeg",
  },
  {
    id: 197,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle8.jpeg",
  },
  {
    id: 198,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle9.jpeg",
  },
  {
    id: 199,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tribangle11.jpeg",
  },
  {
    id: 200,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tribangle12.jpeg",
  },
  {
    id: 201,
    name: "Tri-Color Bangles",
    image: "../../tricolor/tri-bangle10.jpeg",
  },
  {
    id: 202,
    name: "Tri-Color Kadha",
    image: "../../tricolor/tri-kadha1.jpeg",
  },
  {
    id: 203,
    name: "Tri-Color Earrings",
    image: "../../tricolor/tri-earing.jpeg",
  },
  {
    id: 204,
    name: "Tri-Color Earrings",
    image: "../../tricolor/tri-earing2.jpeg",
  },
  {
    id: 205,
    name: "Tri-Color Hairband",
    image: "../../tricolor/tricolor-hairband1.jpeg",
  },
  {
    id: 206,
    name: "Tri-Color Hairband",
    image: "../../tricolor/tri-hairband2.jpeg",
  },
  {
    id: 207,
    name: "Tri-Color Dupatta",
    image: "../../tricolor/tri-dupatta.jpeg",
  },
  {
    id: 480,
    name: "Initial DIY Kit",
    image: "../../personalised/name-kit.jpg",
    price: 320,
  },
  {
    id: 484,
    name: "Name Magnet",
    image: "../../personalised/name.jpeg",
    price: 220,
  },
  {
    id: 485,
    name: "Baby Hamper Set",
    image: "../../personalised/baby.jpeg",
    price: 799,
  },
  {
    id: 486,
    name: "Bottle & Drawing Set",
    image: "../../personalised/student.jpeg",
    price: 799,
  },
  {
    id: 208,
    name: "Personalised",
    image: "../../personalised/frame1.jpeg",
  },
  {
    id: 209,
    name: "Personalised",
    image: "../../personalised/frame2.jpeg",
  },
  {
    id: 210,
    name: "Personalised",
    image: "../../personalised/frame3.jpeg",
  },
  {
    id: 211,
    name: "Personalised",
    image: "../../personalised/frame4.jpeg",
  },
  {
    id: 212,
    name: "Personalised",
    image: "../../personalised/frame5.jpeg",
  },
  {
    id: 213,
    name: "Personalised",
    image: "../../personalised/frame6.jpeg",
  },
  {
    id: 214,
    name: "Personalised",
    image: "../../personalised/frame7.jpeg",
  },
  {
    id: 215,
    name: "Personalised",
    image: "../../personalised/frame8.jpeg",
  },
  {
    id: 216,
    name: "Personalised",
    image: "../../personalised/frame9.jpeg",
  },
  {
    id: 217,
    name: "Personalised",
    image: "../../personalised/frame10.jpeg",
  },
  {
    id: 435,
    name: "Personalised",
    image: "../../personalised/frame11.jpeg",
    // price: "200",
  },
  {
    id: 436,
    name: "Personalised",
    image: "../../personalised/frame12.jpeg",
    // price: "200",
  },
  {
    id: 437,
    name: "Personalised",
    image: "../../personalised/frame13.jpeg",
    // price: "200",
  },
  {
    id: 438,
    name: "Personalised",
    image: "../../personalised/frame14.jpeg",
    // price: "200",
  },
  {
    id: 439,
    name: "Personalised",
    image: "../../personalised/frame15.jpeg",
    // price: "200",
  },
  {
    id: 441,
    name: "Personalised",
    image: "../../personalised/frame17.jpeg",
    // price: "200",
  },
  {
    id: 442,
    name: "Personalised",
    image: "../../personalised/frame18.jpeg",
    // price: "200",
  },
  {
    id: 444,
    name: "Personalised",
    image: "../../personalised/frame20.jpeg",
    // price: "200",
  },
  {
    id: 445,
    name: "Personalised",
    image: "../../personalised/frame21.jpeg",
    // price: "200",
  },
  {
    id: 447,
    name: "Personalised",
    image: "../../personalised/frame23.jpeg",
    price: 499,
  },
  {
    id: 448,
    name: "Personalised",
    image: "../../personalised/pillow1.jpeg",
    // price: "200",
  },
  {
    id: 218,
    name: "Personalised",
    image: "../../personalised/still1.jpeg",
  },
  {
    id: 219,
    name: "Personalised",
    image: "../../personalised/still2.jpeg",
  },
  {
    id: 220,
    name: "Personalised",
    image: "../../personalised/still3.jpeg",
  },
  {
    id: 222,
    name: "Personalised",
    image: "../../personalised/still5.jpeg",
  },
  {
    id: 223,
    name: "Personalised",
    image: "../../personalised/still6.jpeg",
  },
  {
    id: 224,
    name: "Personalised",
    image: "../../personalised/still7.jpeg",
  },
  {
    id: 225,
    name: "Personalised",
    image: "../../personalised/still8.jpeg",
  },
  {
    id: 226,
    name: "Personalised",
    image: "../../personalised/still9.jpeg",
  },
  {
    id: 227,
    name: "Personalised",
    image: "../../personalised/still10.jpeg",
  },
  {
    id: 228,
    name: "Personalised",
    image: "../../personalised/still11.jpeg",
  },
  {
    id: 229,
    name: "Personalised",
    image: "../../personalised/still12.jpeg",
  },
  {
    id: 230,
    name: "Personalised",
    image: "../../personalised/still13.jpeg",
  },
  {
    id: 451,
    name: "Personalised",
    image: "../../personalised/still14.jpeg",
  },
  {
    id: 231,
    name: "Personalised",
    image: "../../personalised/bottle1.jpeg",
  },
  {
    id: 232,
    name: "Personalised",
    image: "../../personalised/bottle2.jpeg",
  },
  {
    id: 233,
    name: "Personalised",
    image: "../../personalised/bottle3.jpeg",
  },
  {
    id: 234,
    name: "Personalised",
    image: "../../personalised/bottle4.jpeg",
  },
  {
    id: 235,
    name: "Personalised",
    image: "../../personalised/bottle5.jpeg",
  },
  {
    id: 236,
    name: "Personalised",
    image: "../../personalised/cap.jpeg",
  },
  {
    id: 237,
    name: "Personalised",
    image: "../../personalised/toy.jpeg",
  },
  {
    id: 238,
    name: "Personalised",
    image: "../../personalised/toy1.jpeg",
  },
  {
    id: 239,
    name: "Personalised",
    image: "../../personalised/toy2.jpeg",
  },
  {
    id: 240,
    name: "Personalised",
    image: "../../personalised/toy3.jpeg",
  },
  {
    id: 241,
    name: "Personalised",
    image: "../../personalised/ut1.jpeg",
  },
  {
    id: 242,
    name: "Personalised",
    image: "../../personalised/ut2.jpeg",
  },
  {
    id: 243,
    name: "Personalised",
    image: "../../personalised/wallet1.jpeg",
  },
  {
    id: 244,
    name: "Personalised",
    image: "../../personalised/wallet2.jpeg",
  },
  {
    id: 245,
    name: "Personalised",
    image: "../../personalised/wallet3.jpeg",
  },
  {
    id: 450,
    name: "Personalised",
    image: "../../personalised/wallet5.jpeg",
    // price: "200",
  },
  {
    id: 246,
    name: "Personalised",
    image: "../../personalised/tiffin1.jpeg",
  },
  {
    id: 247,
    name: "Personalised",
    image: "../../personalised/tiffin2.jpeg",
  },
  {
    id: 248,
    name: "Personalised",
    image: "../../personalised/tiffin3.jpeg",
  },
  {
    id: 249,
    name: "Personalised",
    image: "../../personalised/Rakhi.jpeg",
  },
  {
    id: 250,
    name: "Personalised",
    image: "../../personalised/rakhi1.jpeg",
  },
  {
    id: 252,
    name: "Personalised",
    image: "../../personalised/rakhi3.jpeg",
  },
  {
    id: 253,
    name: "Personalised",
    image: "../../personalised/card1.jpeg",
  },
  {
    id: 254,
    name: "Personalised",
    image: "../../personalised/clock1.jpeg",
  },
  {
    id: 452,
    name: "Personalised",
    image: "../../personalised/cup1.jpeg",
  },
  {
    id: 453,
    name: "Personalised",
    image: "../../personalised/cup2.jpeg",
  },
  {
    id: 454,
    name: "Personalised",
    image: "../../personalised/cup3.jpeg",
  },
  {
    id: 455,
    name: "Personalised",
    image: "../../personalised/cup4.jpeg",
  },
  {
    id: 456,
    name: "Personalised",
    image: "../../personalised/cup5.jpeg",
  },
  {
    id: 457,
    name: "Personalised",
    image: "../../personalised/cup6.jpeg",
  },
  {
    id: 458,
    name: "Personalised",
    image: "../../personalised/cup7.jpeg",
  },
  {
    id: 459,
    name: "Personalised",
    image: "../../personalised/board1.jpeg",
  },
  {
    id: 460,
    name: "Personalised",
    image: "../../personalised/bag1.jpeg",
  },
  {
    id: 255,
    name: "Bangles",
    image: "../../hariyaliteej/bangle.jpeg",
    // price: 100,
  },
  {
    id: 256,
    name: "Bangles",
    image: "../../hariyaliteej/bangle1.jpeg",
    // price: "100",
  },
  {
    id: 257,
    name: "Bangles",
    image: "../../hariyaliteej/bangle2.jpeg",
    // price: "100",
  },
  {
    id: 258,
    name: "Bangles",
    image: "../../hariyaliteej/bangle3.jpeg",
    // price: "100",
  },
  {
    id: 259,
    name: "Bangles",
    image: "../../hariyaliteej/bangle4.jpeg",
    // price: "100",
  },
  {
    id: 260,
    name: "Bangles",
    image: "../../hariyaliteej/bangle5.jpeg",
    // price: "100",
  },
  {
    id: 261,
    name: "Bangles",
    image: "../../hariyaliteej/bangle6.jpeg",
    // price: "100",
  },
  {
    id: 262,
    name: "Bangles",
    image: "../../hariyaliteej/bangle7.jpeg",
    // price: "100",
  },
  {
    id: 263,
    name: "Bangles",
    image: "../../hariyaliteej/bangle8.jpeg",
    // price: "100",
  },
  {
    id: 264,
    name: "Bangles",
    image: "../../hariyaliteej/bangle9.jpeg",
    // price: "100",
  },
  {
    id: 265,
    name: "Bangles",
    image: "../../hariyaliteej/bangle10.jpeg",
    // price: "100",
  },
  {
    id: 266,
    name: "Bangles",
    image: "../../hariyaliteej/bangle11.jpeg",
    // price: "100",
  },
  {
    id: 267,
    name: "Bangles",
    image: "../../hariyaliteej/bangle12.jpeg",
    // price: "100",
  },
  {
    id: 268,
    name: "Bangles",
    image: "../../hariyaliteej/bangle13.jpeg",
    // price: "100",
  },
  {
    id: 269,
    name: "Bangles",
    image: "../../hariyaliteej/bangle14.jpeg",
    // price: "100",
  },
  {
    id: 270,
    name: "Bangles",
    image: "../../hariyaliteej/bangle15.jpeg",
    // price: "100",
  },
  {
    id: 271,
    name: "Bangles",
    image: "../../hariyaliteej/bangle16.jpeg",
    // price: "100",
  },
  {
    id: 272,
    name: "Bangles",
    image: "../../hariyaliteej/bangle17.jpeg",
    // price: "100",
  },
  {
    id: 273,
    name: "Bindis",
    image: "../../hariyaliteej/bindi.jpeg",
    // price: "100",
  },
  {
    id: 274,
    name: "Alta",
    image: "../../hariyaliteej/alta.jpeg",
    // price: "100",
  },
  {
    id: 275,
    name: "Sindoor",
    image: "../../hariyaliteej/sindoor.jpeg",
    // price: "100",
  },
];

//481

export const carousel = {
  name: "cara",
  images: [
    "../../kids/toy3.jpeg",
    "../../kids/toy4.jpeg",
    "../../kids/toy5.jpeg",
    "../../kids/toy6.jpeg",
  ],
  name: "carousel",
  images: [
    "../../kids/toy3.jpeg",
    "../../kids/toy4.jpeg",
    "../../kids/toy5.jpeg",
    "../../kids/toy6.jpeg",
  ],
};
