export const actionType = {
  ADDTOCART: "ADDTOCART",
  REMOVEFROMCART: "REMOVEFROMCART",
  INCREMENTQUANTITY: "INCREMENTQUANTITY",
  DECREMENTQUANTITY: "DECREMENTQUANTITY",

  ADDTOWISHLIST: "ADDTOWISHLIST",
  REMOVEFROMWISHLIST: "REMOVEFROMWISHLIST",
};
